### ISSUE TITLE
Write PHP program

### ISSUE THREAD

**Issue by sandrahbackstrom** [aronstrandberg/MVK15#50]
Convert data from database to geoJson

**Comment by sandrahbackstrom** [comment]
Shappe and I are working on this. 

How should we convert the data to geojson? manually? 
How should the connection be between PHP and website? 

We need the correct database properties to be able to connect, set up the correct database.

**Comment by karlek** [comment]
You could search for a PHP library which already converts to GeoJSON. 

When you ask 'how should the connection be', are you asking how to connect to the database with PHP?
If so there are multiple ways, the best is PDO.
https://php.net/manual/en/book.pdo.php

What do you mean about correcting the database properties?

**Comment by sandrahbackstrom** [comment]
There is no geoJson convertion function. There is however a Json function. I figure that is not what we want. If you look at the code, its on github, we have tried to do it manually.

The connection, as in should we push or should JS ask for data. 

We have updated the database, adding one more attribute (read) from the database in SRS1. Look at the code and you'll see why and how we use it.

**Comment by aronstrandberg** [comment]
I think the best way is JS will poll for new data using ajax. @karlek?

**Comment by karlek** [comment]
I google'd and there seems to be a few unoffical PHP libraries for GeoJSON conversion however since my knowledge about GeoJSON is lacking I'll need to read about about them first.

The best way, as you said @sandrahbackstrom and @aronstrandberg is for the JS to ask/pull the data.
(In PHP you could use $_GET requests for this)

Ah, I see. We probably want a reset feature for the read-attribute when we are testing, should a make an issue for that? Or is it easier to do it manually from the shell?

**Comment by karlek** [comment]
Well your solutions seems to be working and looks clean!

**Comment by sandrahbackstrom** [comment]
Done!
