### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#9]
The data that will be collected from the mobile unit is, at this stage:

* Longitude
* Latitude
* Timestamp

Construct a fitting database schema for this information. Remember to check with the frontend-devs if they've got any suggestions / opinions.

**Comment by shappe** [comment]
Finally understood this Github thingy.

I was thinking something along the lines of this?
![schema](https://cloud.githubusercontent.com/assets/7439210/6177437/27c685be-b307-11e4-93e3-5573cb878bcc.png)
For each drone, there can be many DroneData rows. Each DroneData entry belongs to a Drone and has its own timestamp, longitude and latitude.
I feel like this schema is very simple and primitive, but maybe it contains all the vitals?

1. Is there anything missing?
2. Should we have an ID for each DroneData entry, or will the DroneID and Timestamp suffice as combined keys? I went ahead and used an ID since I thought it'd be smoother to use.

**Comment by nejlika** [comment]
I don't think we can access the altitude of the drone, we could use another sensor for it but that would just add complexity at the moment.

**Comment by karlek** [comment]
I got an idea, what about adding DroneModel as a separate table with ID and MaxWeight?

**Comment by shappe** [comment]
Sounds great!

Should I separate the Latitude and Longitude from DroneData into a separate table 'Location' ?

**Comment by karlek** [comment]
Yeah, I think the logical abstraction would be clearer :camel:

**Comment by shappe** [comment]
So does this look better? Any suggestions? Anything missing?
![schema2](https://cloud.githubusercontent.com/assets/7439210/6227276/d1e244b8-b69d-11e4-9f0f-dd1913b7f719.png)

**Comment by karlek** [comment]
Looks great man, nice work!

**Comment by karlek** [comment]
Haha, shit forgot that we need to specify types.

**Comment by shappe** [comment]
Do you mean like this?
![schema3](https://cloud.githubusercontent.com/assets/7439210/6227347/ae92d918-b69e-11e4-88eb-7d7c4772fb5c.png)

**Comment by karlek** [comment]
Sweet! Only thing left now is to convert this to a create table query. However that is another issue. Nice!
